/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
// package doc2.managers;
package zyfralab.homeproj;

 import javax.swing.ImageIcon;
 import javax.swing.*;



/**
 *
 * @author smzubarev
 */
public class EditTCForm extends javax.swing.JFrame {
   
    private Reporter repo = null;
    private Array atModel = null;
    private TCKETypeModel tckeModel = null;
    private TCEditDiagModel tcdeModel = null;
    
    /**
     * Creates new form EditTCForm
     */
    public EditTCForm(Reporter rep) 
    {
        initComponents();
        repo = rep;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblActions = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKETypeTC = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblEditDiag = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setLocation(new java.awt.Point(1, 150));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblActions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "TC ID", "Act ID", "Action", "Time, min", "Cost, units"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblActions);
        if (tblActions.getColumnModel().getColumnCount() > 0) {
            tblActions.getColumnModel().getColumn(0).setMinWidth(45);
            tblActions.getColumnModel().getColumn(0).setPreferredWidth(45);
            tblActions.getColumnModel().getColumn(0).setMaxWidth(45);
            tblActions.getColumnModel().getColumn(1).setMinWidth(45);
            tblActions.getColumnModel().getColumn(1).setPreferredWidth(45);
            tblActions.getColumnModel().getColumn(1).setMaxWidth(45);
            tblActions.getColumnModel().getColumn(2).setMinWidth(45);
            tblActions.getColumnModel().getColumn(2).setPreferredWidth(45);
            tblActions.getColumnModel().getColumn(2).setMaxWidth(45);
            tblActions.getColumnModel().getColumn(4).setMinWidth(75);
            tblActions.getColumnModel().getColumn(4).setPreferredWidth(75);
            tblActions.getColumnModel().getColumn(4).setMaxWidth(57);
            tblActions.getColumnModel().getColumn(5).setMinWidth(75);
            tblActions.getColumnModel().getColumn(5).setPreferredWidth(75);
            tblActions.getColumnModel().getColumn(5).setMaxWidth(75);
        }

        jLabel1.setText("Edit Actions for Techcard");

        tblKETypeTC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "KE Type", "TC ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblKETypeTC);
        if (tblKETypeTC.getColumnModel().getColumnCount() > 0) {
            tblKETypeTC.getColumnModel().getColumn(0).setMinWidth(45);
            tblKETypeTC.getColumnModel().getColumn(0).setPreferredWidth(45);
            tblKETypeTC.getColumnModel().getColumn(0).setMaxWidth(45);
        }

        jLabel2.setText("Connect Techcards to KE Type");

        tblEditDiag.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Diag ID", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblEditDiag);
        if (tblEditDiag.getColumnModel().getColumnCount() > 0) {
            tblEditDiag.getColumnModel().getColumn(0).setMinWidth(45);
            tblEditDiag.getColumnModel().getColumn(0).setPreferredWidth(45);
            tblEditDiag.getColumnModel().getColumn(0).setMaxWidth(45);
            tblEditDiag.getColumnModel().getColumn(1).setMinWidth(95);
            tblEditDiag.getColumnModel().getColumn(1).setPreferredWidth(95);
            tblEditDiag.getColumnModel().getColumn(1).setMaxWidth(95);
        }

        jLabel3.setText("Edit Techcards Diagnoses");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
      /*  ImageIcon img = new ImageIcon("C:/Users/Nikita/Documents/GitHub/Homeproject/Homeproj/src/main/java/zyfralab/homeproj");
        setIconImage(img.getImage()); */

        actTbl_Init();
        tcKETypeTbl_Init(); 
        tblEditDiag_Init();
    }//GEN-LAST:event_formWindowOpened
    
    // Methods to work with Actions table
    private void actTbl_Init()
    {
            atModel = new Array(); //(repo)
      //   tblActions.setAutoCreateColumnsFromModel(false);
      //   tblActions.setModel(atModel);        
    }
 
    private void tcKETypeTbl_Init()
    {
        tckeModel = new TCKETypeModel(repo);
        tckeModel.initModel();
        tblKETypeTC.setAutoCreateColumnsFromModel(false);
        tblKETypeTC.setModel(tckeModel);                
    }
    private void tblEditDiag_Init()
    {
        tcdeModel = new TCEditDiagModel(repo);
        tcdeModel.initModel();
        tblEditDiag.setAutoCreateColumnsFromModel(false);
        tblEditDiag.setModel(tcdeModel);  
    }

    public static void main(String x[])
    {
        SwingUtilities.invokeLater(new Runnable()
        {
            public void run()
            {
                new EditTCForm(new Reporter()).setVisible(true);
            }
        });
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblActions;
    private javax.swing.JTable tblEditDiag;
    private javax.swing.JTable tblKETypeTC;
    // End of variables declaration//GEN-END:variables
}
